export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_PENDING = "LOGIN_USER_PENDING";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const REGISTER_USER_PENDING = "REGISTER_USER_PENDING";

export const UPDATE_CHATS_SUCCESS = "UPDATE_CHATS_SUCCESS";
export const CREATE_CHATS_ERROR = "CREATE_CHATS_ERROR";
export const CREATE_CHATS_PENDING = "CREATE_CHATS_PENDING";
export const CREATE_CHATS_SUCCESS = "CREATE_CHATS_SUCCESS";
export const FETCH_CHATS_ERROR = "FETCH_CHATS_ERROR";
export const FETCH_CHATS_PENDING = "FETCH_CHATS_PENDING";
export const FETCH_CHATS_SUCCESS = "FETCH_CHATS_SUCCESS";

export const FETCH_NEWS_ERROR = "FETCH_NEWS_ERROR";
export const FETCH_NEWS_PENDING = "FETCH_NEWS_PENDING";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const CREATE_NEWS_ERROR = "CREATE_NEWS_ERROR";
export const CREATE_NEWS_PENDING = "CREATE_NEWS_PENDING";
export const CREATE_NEWS_SUCCESS = "CREATE_NEWS_SUCCESS";
export const UPDATE_NEWS_ERROR = "UPDATE_NEWS_ERROR";
export const UPDATE_NEWS_PENDING = "UPDATE_NEWS_PENDING";
export const UPDATE_NEWS_SUCCESS = "UPDATE_NEWS_SUCCESS";
export const DELETE_NEWS = "DELETE_NEWS";
export const DELETE_NEWS_ERROR = "DELETE_NEWS_ERROR";
export const DELETE_NEWS_PENDING = "DELETE_NEWS_PENDING";

export const CLEAN_ERROR = "CLEAN_ERROR";
